In [1]:
import numpy as np

In [13]:
a=np.array([[11,12,13],[14,15,16],[17,18,19],[11,20,21]])

In [14]:
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [11, 20, 21]])

In [15]:
a.shape

(4, 3)

In [16]:
a.size

12

In [17]:
len(a)

4

In [18]:
a.ndim

2

In [19]:
a[:,0]

array([11, 14, 17, 11])

In [20]:
a[0,:]

array([11, 12, 13])

In [21]:
a[1,:]

array([14, 15, 16])

In [22]:
a[2:4,]

array([[17, 18, 19],
       [11, 20, 21]])

In [23]:
a[2:4,1:3]

array([[18, 19],
       [20, 21]])

In [30]:
a[0::3,]

array([[11, 12, 13],
       [11, 20, 21]])

In [31]:
a[0::3,0:3:2]

array([[11, 13],
       [11, 21]])

In [32]:
a[::-1,::-1]

array([[21, 20, 11],
       [19, 18, 17],
       [16, 15, 14],
       [13, 12, 11]])

In [35]:
a.sum()

187

a.sum(axis=0)

In [36]:
a.sum(axis=0)

array([53, 65, 69])

In [37]:
a.mean()

15.583333333333334

In [39]:
a.max()

21

In [40]:
a.std()

3.32812092461931

In [41]:
a.min()

11